// AUTO-GENERATED by scripts/generate-search-index.mjs
// Do not edit manually. Run: node scripts/generate-search-index.mjs
// Generated at: 2026-04-05T19:59:44.397Z

import {
  ArrowsClockwise,
  Brain,
  Browser,
  Buildings,
  ChalkboardTeacher,
  ChartLineUp,
  CurrencyDollar,
  Export,
  FilePdf,
  Flag,
  Gear,
  GitBranch,
  Heartbeat,
  House,
  IdentificationBadge,
  Key,
  Lightning,
  ListBullets,
  Megaphone,
  PaperPlaneTilt,
  Percent,
  Prohibit,
  Receipt,
  Scales,
  ShieldCheck,
  ShieldWarning,
  Student,
  ToggleRight,
  TreeStructure,
  UserSwitch,
  UsersThree,
  VideoCamera,
  Wallet,
  Wrench,
} from "@phosphor-icons/react";

import { usageKPIs, usageSparklines, dailyTokenBurn, latencyMetrics, topConsumers, keysKPIs, keysSparklines, apiKeys, workflowKPIs, workflowSparklines, workflows, ethicsKPIs, ethicsSparklines, safeguards, regionalScopes } from "./ai/aiMockData";
import { broadcastKPIs, broadcastSparklines, broadcastTemplates, broadcastLogs } from "./broadcast/broadcastMockData";
import { churnKPIs, churnSparklines, atRiskUsers, sentimentFlags } from "./churn/churnMockData";
import { classKPIs, liveSessions, pastClasses } from "./classes/classMockData";
import { cmsKPIs, cmsSparklines, cmsPages, sampleBlocks, seoAudit, cmsMedia } from "./cms/cmsMockData";
import { commissionKPIs, commissionSparklines, commissionRules, fxRates, taxRules } from "./commission/commissionMockData";
import { disputeKPIs, disputes } from "./disputes/disputeMockData";
import { revenueKPIs, revenueSparklines, transactions, payoutKPIs, payoutSparklines, payouts, refundKPIs, refundSparklines, refunds, invoiceKPIs, invoiceSparklines, invoices } from "./financial/financialMockData";
import { impersonationKPIs, impersonationSparklines, impersonationSessions, impersonationLogs } from "./impersonation/impersonationMockData";
import { kycKPIs, kycApplicants } from "./kyc/kycMockData";
import { leadKPIs, leads } from "./leads/leadMockData";
import { opsMetrics, liveSessions as mockData_liveSessions, governanceQueue, auditTrail, adminNotifications } from "./mockData";
import { moderationKPIs, flaggedItems } from "./moderation/moderationMockData";
import { securityKPIs, securitySparklines, threatEvents, activeSessions, ipRules, securityPolicies } from "./security/securityMockData";
import { staffKPIs, staffMembers, rbacPermissions } from "./staff/staffMockData";
import { studentKPIs, students } from "./students/studentMockData";
import { auditKPIs, auditSparklines, auditLogs, flagKPIs, flagSparklines, featureFlags, emergencyKPIs, emergencySparklines, killSwitches, overrideKPIs, overrideSparklines, systemOverrides, overrideLogs } from "./system/systemMockData";
import { taxonomyKPIs, taxonomySparklines, subjectTree, featuredTutors } from "./taxonomy/taxonomyMockData";
import { teacherKPIs, teachers } from "./teachers/teacherMockData";
import { tenantKPIs, tenantSparklines, tenants, bulkInvites, creditAllocations } from "./tenants/tenantMockData";

export type SearchResultType = "page" | "action" | "session" | "audit" | "cms" | "student" | "teacher" | "transaction";

export interface SearchItem {
  id: string;
  type: SearchResultType;
  title: string;
  subtitle: string;
  iconName: string;
  href?: string;
}

export const TYPE_LABELS: Record<SearchResultType, string> = {
  page: "Pages", action: "Actions", session: "Sessions", audit: "Audit Logs",
  cms: "CMS Pages", student: "Students", teacher: "Teachers", transaction: "Transactions",
};

export const TYPE_ORDER: SearchResultType[] = ["action", "page", "session", "audit", "cms"];

// ── NAV PAGES (auto-discovered from /app/dashboard/admin/*) ──

export const NAV_PAGES: SearchItem[] = [
  { id: "nav-home", type: "page", title: "Health Dashboard", subtitle: "Platform Command", iconName: "House", href: "/dashboard/admin" },
  { id: "nav-ai-ethics", type: "page", title: "Ethics Controls", subtitle: "AI Governance", iconName: "ToggleRight", href: "/dashboard/admin/ai-ethics" },
  { id: "nav-ai-usage", type: "page", title: "AI Usage Metrics", subtitle: "AI Governance", iconName: "Brain", href: "/dashboard/admin/ai-usage" },
  { id: "nav-ai-workflows", type: "page", title: "AI Workflow Rules", subtitle: "AI Governance", iconName: "GitBranch", href: "/dashboard/admin/ai-workflows" },
  { id: "nav-analytics", type: "page", title: "Global Analytics", subtitle: "Platform Command", iconName: "ChartLineUp", href: "/dashboard/admin/analytics" },
  { id: "nav-api-keys", type: "page", title: "Quotas & API Keys", subtitle: "AI Governance", iconName: "Key", href: "/dashboard/admin/api-keys" },
  { id: "nav-audit", type: "page", title: "Audit Logs", subtitle: "System & Audit", iconName: "ListBullets", href: "/dashboard/admin/audit" },
  { id: "nav-broadcast", type: "page", title: "Broadcast Hub", subtitle: "Orchestration", iconName: "PaperPlaneTilt", href: "/dashboard/admin/broadcast" },
  { id: "nav-churn", type: "page", title: "Churn Prediction", subtitle: "Orchestration", iconName: "Heartbeat", href: "/dashboard/admin/churn" },
  { id: "nav-classes", type: "page", title: "Class Monitor", subtitle: "Live Ops", iconName: "VideoCamera", href: "/dashboard/admin/classes" },
  { id: "nav-cms", type: "page", title: "CMS Pages", subtitle: "Website", iconName: "Browser", href: "/dashboard/admin/cms" },
  { id: "nav-commission", type: "page", title: "Commission Engine", subtitle: "Orchestration", iconName: "Percent", href: "/dashboard/admin/commission" },
  { id: "nav-disputes", type: "page", title: "Dispute Resolution", subtitle: "Live Ops", iconName: "Scales", href: "/dashboard/admin/disputes" },
  { id: "nav-emergency", type: "page", title: "Emergency Controls", subtitle: "System & Audit", iconName: "Lightning", href: "/dashboard/admin/emergency" },
  { id: "nav-flags", type: "page", title: "Feature Flags", subtitle: "System & Audit", iconName: "Flag", href: "/dashboard/admin/flags" },
  { id: "nav-impersonation", type: "page", title: "Impersonation", subtitle: "Orchestration", iconName: "UserSwitch", href: "/dashboard/admin/impersonation" },
  { id: "nav-invoices", type: "page", title: "Invoices & Taxes", subtitle: "Financial", iconName: "Receipt", href: "/dashboard/admin/invoices" },
  { id: "nav-kyc", type: "page", title: "KYC Pipeline", subtitle: "User Lifecycle", iconName: "IdentificationBadge", href: "/dashboard/admin/kyc" },
  { id: "nav-leads", type: "page", title: "Lead Management", subtitle: "Live Ops", iconName: "Megaphone", href: "/dashboard/admin/leads" },
  { id: "nav-moderation", type: "page", title: "Content Moderation", subtitle: "Live Ops", iconName: "ShieldCheck", href: "/dashboard/admin/moderation" },
  { id: "nav-overrides", type: "page", title: "Overrides", subtitle: "System & Audit", iconName: "Wrench", href: "/dashboard/admin/overrides" },
  { id: "nav-payouts", type: "page", title: "Payouts", subtitle: "Financial", iconName: "Wallet", href: "/dashboard/admin/payouts" },
  { id: "nav-refunds", type: "page", title: "Refunds", subtitle: "Financial", iconName: "ArrowsClockwise", href: "/dashboard/admin/refunds" },
  { id: "nav-revenue", type: "page", title: "Revenue & Escrow", subtitle: "Financial", iconName: "CurrencyDollar", href: "/dashboard/admin/revenue" },
  { id: "nav-security", type: "page", title: "Security Center", subtitle: "System & Audit", iconName: "ShieldWarning", href: "/dashboard/admin/security" },
  { id: "nav-staff", type: "page", title: "Agents / Staff", subtitle: "User Lifecycle", iconName: "UsersThree", href: "/dashboard/admin/staff" },
  { id: "nav-students", type: "page", title: "Students", subtitle: "User Lifecycle", iconName: "Student", href: "/dashboard/admin/students" },
  { id: "nav-taxonomy", type: "page", title: "Taxonomy", subtitle: "Orchestration", iconName: "TreeStructure", href: "/dashboard/admin/taxonomy" },
  { id: "nav-teachers", type: "page", title: "Teachers", subtitle: "User Lifecycle", iconName: "ChalkboardTeacher", href: "/dashboard/admin/teachers" },
  { id: "nav-tenants", type: "page", title: "B2B Tenants", subtitle: "Orchestration", iconName: "Buildings", href: "/dashboard/admin/tenants" },
];

// ── ROUTE LABELS (for header breadcrumb) ──

export const ROUTE_LABELS: Record<string, string> = {
  "/dashboard/admin": "Health Dashboard",
  "/dashboard/admin/ai-ethics": "Ethics Controls",
  "/dashboard/admin/ai-usage": "AI Usage Metrics",
  "/dashboard/admin/ai-workflows": "AI Workflow Rules",
  "/dashboard/admin/analytics": "Global Analytics",
  "/dashboard/admin/api-keys": "Quotas & API Keys",
  "/dashboard/admin/audit": "Audit Logs",
  "/dashboard/admin/broadcast": "Broadcast Hub",
  "/dashboard/admin/churn": "Churn Prediction",
  "/dashboard/admin/classes": "Class Monitor",
  "/dashboard/admin/cms": "CMS Pages",
  "/dashboard/admin/commission": "Commission Engine",
  "/dashboard/admin/disputes": "Dispute Resolution",
  "/dashboard/admin/emergency": "Emergency Controls",
  "/dashboard/admin/flags": "Feature Flags",
  "/dashboard/admin/impersonation": "Impersonation",
  "/dashboard/admin/invoices": "Invoices & Taxes",
  "/dashboard/admin/kyc": "KYC Pipeline",
  "/dashboard/admin/leads": "Lead Management",
  "/dashboard/admin/moderation": "Content Moderation",
  "/dashboard/admin/overrides": "Overrides",
  "/dashboard/admin/payouts": "Payouts",
  "/dashboard/admin/refunds": "Refunds",
  "/dashboard/admin/revenue": "Revenue & Escrow",
  "/dashboard/admin/security": "Security Center",
  "/dashboard/admin/staff": "Agents / Staff",
  "/dashboard/admin/students": "Students",
  "/dashboard/admin/taxonomy": "Taxonomy",
  "/dashboard/admin/teachers": "Teachers",
  "/dashboard/admin/tenants": "B2B Tenants",
};

export const ROUTE_GROUPS: Record<string, string> = {
  "/dashboard/admin/ai-ethics": "AI Governance",
  "/dashboard/admin/ai-usage": "AI Governance",
  "/dashboard/admin/ai-workflows": "AI Governance",
  "/dashboard/admin/analytics": "Platform Command",
  "/dashboard/admin/api-keys": "AI Governance",
  "/dashboard/admin/audit": "System & Audit",
  "/dashboard/admin/broadcast": "Orchestration",
  "/dashboard/admin/churn": "Orchestration",
  "/dashboard/admin/classes": "Live Ops",
  "/dashboard/admin/cms": "Website",
  "/dashboard/admin/commission": "Orchestration",
  "/dashboard/admin/disputes": "Live Ops",
  "/dashboard/admin/emergency": "System & Audit",
  "/dashboard/admin/flags": "System & Audit",
  "/dashboard/admin/impersonation": "Orchestration",
  "/dashboard/admin/invoices": "Financial",
  "/dashboard/admin/kyc": "User Lifecycle",
  "/dashboard/admin/leads": "Live Ops",
  "/dashboard/admin/moderation": "Live Ops",
  "/dashboard/admin/overrides": "System & Audit",
  "/dashboard/admin/payouts": "Financial",
  "/dashboard/admin/refunds": "Financial",
  "/dashboard/admin/revenue": "Financial",
  "/dashboard/admin/security": "System & Audit",
  "/dashboard/admin/staff": "User Lifecycle",
  "/dashboard/admin/students": "User Lifecycle",
  "/dashboard/admin/taxonomy": "Orchestration",
  "/dashboard/admin/teachers": "User Lifecycle",
  "/dashboard/admin/tenants": "Orchestration",
};

// ── SIDEBAR NAV GROUPS ──

const GROUP_ORDER = ["Platform Command", "User Lifecycle", "Live Ops", "Financial", "AI Governance", "Orchestration", "Website", "System & Audit"];

export interface SidebarGroup {
  label: string;
  items: { name: string; href: string; iconName: string }[];
}

export const SIDEBAR_GROUPS: SidebarGroup[] = GROUP_ORDER.map((g) => ({
  label: g.toUpperCase(),
  items: NAV_PAGES.filter((p) => p.subtitle === g).map((p) => ({
    name: p.title,
    href: p.href!,
    iconName: p.iconName,
  })),
})).filter((g) => g.items.length > 0);

// ── ADMIN ACTIONS ──

export const ADMIN_ACTIONS: SearchItem[] = [
  { id: "act-impersonate-student", type: "action", title: "Login as Student", subtitle: "Impersonate a student account", iconName: "Student", href: "/dashboard/admin/impersonation" },
  { id: "act-impersonate-teacher", type: "action", title: "Login as Teacher", subtitle: "Impersonate a teacher account", iconName: "ChalkboardTeacher", href: "/dashboard/admin/impersonation" },
  { id: "act-export-audit", type: "action", title: "Export Audit Trail", subtitle: "Download as CSV or PDF", iconName: "Export", href: "/dashboard/admin/audit" },
  { id: "act-export-revenue", type: "action", title: "Export Revenue Report", subtitle: "Financial data export", iconName: "FilePdf", href: "/dashboard/admin/revenue" },
  { id: "act-kill-switch", type: "action", title: "Emergency Kill Switches", subtitle: "Halt bookings, payouts, or platform", iconName: "Prohibit", href: "/dashboard/admin/emergency" },
  { id: "act-feature-flag", type: "action", title: "Toggle Feature Flag", subtitle: "Enable or disable platform features", iconName: "Flag", href: "/dashboard/admin/flags" },
  { id: "act-batch-payout", type: "action", title: "Initiate Batch Payout", subtitle: "Process pending teacher settlements", iconName: "Wallet", href: "/dashboard/admin/payouts" },
  { id: "act-settings", type: "action", title: "Account Settings", subtitle: "Manage your admin profile", iconName: "Gear" },
];

// ── DYNAMIC DATA INDEX (from mock data files) ──

export function buildSearchIndex(): SearchItem[] {
  const items: SearchItem[] = [...NAV_PAGES, ...ADMIN_ACTIONS];

  // From classMockData.ts → liveSessions
  try {
    if (Array.isArray(liveSessions)) {
      liveSessions.forEach((s: any, i: number) => {
        const title = s.sessionId ? `${s.sessionId} — ${s.subject || ""}` : s.host ? `${s.host} — ${s.subject || ""}` : `Session ${i}`;
        const subtitle = [s.teacher, s.student, s.region, s.duration, s.status].filter(Boolean).join(" · ");
        items.push({ id: `ses-classMockData-${i}`, type: "session", title, subtitle, iconName: "VideoCamera", href: "/dashboard/admin/classes" });
      });
    }
  } catch {}

  // From cmsMockData.ts → cmsKPIs
  try {
    if (Array.isArray(cmsKPIs)) {
      cmsKPIs.forEach((p: any, i: number) => {
        if (p.title && p.slug) {
          items.push({ id: `cms-cmsMockData-${i}`, type: "cms", title: p.title, subtitle: [p.slug, p.status, p.seoScore ? `SEO: ${p.seoScore}` : ""].filter(Boolean).join(" · "), iconName: "Browser", href: "/dashboard/admin/cms" });
        }
      });
    }
  } catch {}

  // From cmsMockData.ts → cmsSparklines
  try {
    if (Array.isArray(cmsSparklines)) {
      cmsSparklines.forEach((p: any, i: number) => {
        if (p.title && p.slug) {
          items.push({ id: `cms-cmsMockData-${i}`, type: "cms", title: p.title, subtitle: [p.slug, p.status, p.seoScore ? `SEO: ${p.seoScore}` : ""].filter(Boolean).join(" · "), iconName: "Browser", href: "/dashboard/admin/cms" });
        }
      });
    }
  } catch {}

  // From cmsMockData.ts → cmsPages
  try {
    if (Array.isArray(cmsPages)) {
      cmsPages.forEach((p: any, i: number) => {
        if (p.title && p.slug) {
          items.push({ id: `cms-cmsMockData-${i}`, type: "cms", title: p.title, subtitle: [p.slug, p.status, p.seoScore ? `SEO: ${p.seoScore}` : ""].filter(Boolean).join(" · "), iconName: "Browser", href: "/dashboard/admin/cms" });
        }
      });
    }
  } catch {}

  // From cmsMockData.ts → seoAudit
  try {
    if (Array.isArray(seoAudit)) {
      seoAudit.forEach((e: any, i: number) => {
        items.push({ id: `audit-cmsMockData-${i}`, type: "audit", title: `${e.action || ""} → ${e.target || ""}`, subtitle: [e.actor, e.timestamp, e.category].filter(Boolean).join(" · "), iconName: "ListBullets", href: "/dashboard/admin/audit" });
      });
    }
  } catch {}

  // From cmsMockData.ts → cmsMedia
  try {
    if (Array.isArray(cmsMedia)) {
      cmsMedia.forEach((p: any, i: number) => {
        if (p.title && p.slug) {
          items.push({ id: `cms-cmsMockData-${i}`, type: "cms", title: p.title, subtitle: [p.slug, p.status, p.seoScore ? `SEO: ${p.seoScore}` : ""].filter(Boolean).join(" · "), iconName: "Browser", href: "/dashboard/admin/cms" });
        }
      });
    }
  } catch {}

  // From impersonationMockData.ts → impersonationSessions
  try {
    if (Array.isArray(impersonationSessions)) {
      impersonationSessions.forEach((s: any, i: number) => {
        const title = s.sessionId ? `${s.sessionId} — ${s.subject || ""}` : s.host ? `${s.host} — ${s.subject || ""}` : `Session ${i}`;
        const subtitle = [s.teacher, s.student, s.region, s.duration, s.status].filter(Boolean).join(" · ");
        items.push({ id: `ses-impersonationMockData-${i}`, type: "session", title, subtitle, iconName: "VideoCamera", href: "/dashboard/admin/classes" });
      });
    }
  } catch {}

  // From mockData.ts → liveSessions (as mockData_liveSessions)
  try {
    if (Array.isArray(mockData_liveSessions)) {
      mockData_liveSessions.forEach((s: any, i: number) => {
        const title = s.sessionId ? `${s.sessionId} — ${s.subject || ""}` : s.host ? `${s.host} — ${s.subject || ""}` : `Session ${i}`;
        const subtitle = [s.teacher, s.student, s.region, s.duration, s.status].filter(Boolean).join(" · ");
        items.push({ id: `ses-mockData-${i}`, type: "session", title, subtitle, iconName: "VideoCamera", href: "/dashboard/admin/classes" });
      });
    }
  } catch {}

  // From mockData.ts → auditTrail
  try {
    if (Array.isArray(auditTrail)) {
      auditTrail.forEach((e: any, i: number) => {
        items.push({ id: `audit-mockData-${i}`, type: "audit", title: `${e.action || ""} → ${e.target || ""}`, subtitle: [e.actor, e.timestamp, e.category].filter(Boolean).join(" · "), iconName: "ListBullets", href: "/dashboard/admin/audit" });
      });
    }
  } catch {}

  // From securityMockData.ts → activeSessions
  try {
    if (Array.isArray(activeSessions)) {
      activeSessions.forEach((s: any, i: number) => {
        const title = s.sessionId ? `${s.sessionId} — ${s.subject || ""}` : s.host ? `${s.host} — ${s.subject || ""}` : `Session ${i}`;
        const subtitle = [s.teacher, s.student, s.region, s.duration, s.status].filter(Boolean).join(" · ");
        items.push({ id: `ses-securityMockData-${i}`, type: "session", title, subtitle, iconName: "VideoCamera", href: "/dashboard/admin/classes" });
      });
    }
  } catch {}

  // From systemMockData.ts → auditKPIs
  try {
    if (Array.isArray(auditKPIs)) {
      auditKPIs.forEach((e: any, i: number) => {
        items.push({ id: `audit-systemMockData-${i}`, type: "audit", title: `${e.action || ""} → ${e.target || ""}`, subtitle: [e.actor, e.timestamp, e.category].filter(Boolean).join(" · "), iconName: "ListBullets", href: "/dashboard/admin/audit" });
      });
    }
  } catch {}

  // From systemMockData.ts → auditSparklines
  try {
    if (Array.isArray(auditSparklines)) {
      auditSparklines.forEach((e: any, i: number) => {
        items.push({ id: `audit-systemMockData-${i}`, type: "audit", title: `${e.action || ""} → ${e.target || ""}`, subtitle: [e.actor, e.timestamp, e.category].filter(Boolean).join(" · "), iconName: "ListBullets", href: "/dashboard/admin/audit" });
      });
    }
  } catch {}

  // From systemMockData.ts → auditLogs
  try {
    if (Array.isArray(auditLogs)) {
      auditLogs.forEach((e: any, i: number) => {
        items.push({ id: `audit-systemMockData-${i}`, type: "audit", title: `${e.action || ""} → ${e.target || ""}`, subtitle: [e.actor, e.timestamp, e.category].filter(Boolean).join(" · "), iconName: "ListBullets", href: "/dashboard/admin/audit" });
      });
    }
  } catch {}

  return items;
}

// ── Stats ──
// Routes discovered: 30
// Mock data files: 20
// Icons used: 34
